import type { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '../styles/mainPage.styles'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    hello
    </Container>
  )
}

export default Home
