import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FaArrowRight } from "react-icons/fa";
import { Container } from "../styles/common.style";
import {
  Button,
  HomePage,
  Left,
  MainHeading,
  Para,
  Right,
} from "../styles/mainPage.style";

const Home: NextPage = () => {
  return (
    <HomePage>
      <Container className="container">
        <Head>
          <title>Video Chat</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Left>
          <MainHeading>
            Stay <span>Always Close</span> <br /> From Now
          </MainHeading>
          <Para>
            Meet live with your favourite ones with a few glance. <br />
            Click below to connect.
          </Para>
          <Button>
            Get Started <FaArrowRight />
          </Button>
        </Left>
        <Right>
          <Image
            src="/bg-main.svg"
            height={500}
            width={500}
            objectFit="contain"
          />
        </Right>
      </Container>
    </HomePage>
  );
};

export default Home;
